name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zincnode/mlir-he:v0.1
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Build MLIR-He
      run: |
        ./scripts/build.sh

    - name: Check MLIR-He
      run: |
        ./scripts/build.sh -t
