name: build

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *' # every day at 12:00 (UTC+8)


jobs:
  Build:
    runs-on: ubuntu-latest
    container: zincnode/mlir-he
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Build & test mlir-he w/o Python bindings
      run: |
        ./scripts/build.sh -t

    - name: Build & test mlir-he w/ Python bindings
      run: |
        ./scripts/build.sh -pb -t

    - name: Build & test mlir-he w/ Python bindings in debug mode
      run: |
        ./scripts/build.sh -pb -d -t
