name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zincnode/mlir-he
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Build mlir-he
      run: |
        ./scripts/build.sh

    - name: Check mlir-he
      run: |
        ./scripts/build.sh -t
